name: 'Inactive'

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is inactive because no updates have been recieved in the past 2 weeks. Remove inactive label or comment, or this will be closed in a week.'
          close-issue-message: 'This issue was closed because it has been inactive for a week.'
          stale-issue-label: 'inactive'

          stale-pr-message: 'This pull request is inactive because no updates have been recieved in the past 2 weeks. Remove inactive label or comment, or this will be closed in a week.'
          close-pr-message: 'This pull request was closed because it has been inactive for a week.'
          stale-pr-label: 'inactive'

          days-before-stale: 14
          days-before-close: 7
          days-before-pr-close: -1